//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pro_Feed
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Benutzer
    {
        public int BenutzerID { get; set; }
        public string Username { get; set; }
        public string Passwort { get; set; }
        public string Email { get; set; }
    }
}
